# Generated by Django 4.2.4 on 2023-08-25 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2023, 8, 25, 23, 14, 37, 625197))),
                ('dateModified', models.DateTimeField(default=datetime.datetime(2023, 8, 25, 23, 14, 37, 625197))),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2023, 8, 25, 23, 14, 37, 625197))),
                ('description', models.CharField(max_length=500)),
                ('blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogsdata')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2023, 8, 25, 23, 14, 37, 625197))),
                ('blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogsdata')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiName', models.CharField(max_length=200)),
                ('ref1', models.CharField(max_length=300)),
                ('ref2', models.CharField(max_length=300)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2023, 8, 25, 23, 14, 37, 626197))),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
