# Generated by Django 4.2.4 on 2023-08-25 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogsdata_comments_likes_loggers_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsdata',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 2, 30, 12, 269083)),
        ),
        migrations.AlterField(
            model_name='blogsdata',
            name='dateModified',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 2, 30, 12, 269083)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 2, 30, 12, 270083)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 2, 30, 12, 269083)),
        ),
        migrations.AlterField(
            model_name='loggers',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 2, 30, 12, 270083)),
        ),
    ]
